"""Pydantic models for wave planning and execution."""

from enum import StrEnum

from pydantic import BaseModel, Field


class WaveType(StrEnum):
    """Classification of deployment wave tiers.

    Waves progress from CANARY (smallest, lowest risk) through
    EARLY_ADOPTER to FULL_ROLLOUT (largest batches, all criticality levels).
    """

    CANARY = "CANARY"
    EARLY_ADOPTER = "EARLY_ADOPTER"
    FULL_ROLLOUT = "FULL_ROLLOUT"


class Wave(BaseModel):
    """A single deployment wave targeting a subset of devices.

    Each wave represents one IoT Job execution delivering firmware
    to the specified devices. Waves are executed sequentially by
    the Step Functions orchestrator.
    """

    wave_number: int = Field(ge=1)
    wave_type: WaveType
    thing_names: list[str] = Field(max_length=500)
    target_count: int
    job_id: str | None = None
    status: str | None = None


class WavePlan(BaseModel):
    """Complete deployment plan containing all waves for a firmware rollout.

    Generated by the deployment agent during the PLAN action and stored
    in the Deployment History table. Contains the ordered sequence of
    waves from canary through full rollout.
    """

    deployment_id: str
    target_version: str
    source_version: str
    firmware_s3_url: str
    waves: list[Wave]
    total_devices: int
